### PR TITLE
Fix use of reserved async keyword introduced in python 3.7

### PR DESCRIPTION
**Pull request by yriveiro**
This PR aims to fix the use of reserved keyword `async` introduced in python 3.7

### CODE REVIEW

**Comment by yriveiro** [comment]
@rgs1, I fixed travis config and now is all green.

**Comment by rgs1** [comment]
@yriveiro thanks! we'll do a release later today/this-weekend.

cc: @Yasumoto

**Comment by rgs1** [comment]
@yriveiro release 1.1.8 — please try.

**Comment by yriveiro** [comment]
I build the PEX file and connected to my zookeeper cluster using python3.7, no errors so far.

**Pull request merged**
